### PR TITLE
Make headerbar in welcome window flat

### PR DESCRIPTION
**Pull request by gregorni**
Just an idea, but I thought since the window is quite empty anyways, it might look good to have the headerbar flat.

### CODE REVIEW

**Review by sonnyp — COMMENTED** [review]
In GNOME; the header bar should only be flat if the rest of the window can be used to drag it.

**Comment by sonnyp** [comment]
I guess if the window isn't supposed to be dragged, it works too. 

No strong opinion here, @tbernard wdyt?

**Comment by gregorni** [comment]
> In GNOME; the header bar should only be flat if the rest of the window can be used to drag it.

Otherwise I could also cover the window in a `Gtk.WindowHandle`, which would make it draggeable (if that's a word). I think it wouldn't do any harm, since the window is, as I said, quite empty.

**Comment by gregorni** [comment]
Speaking of making the window draggeable anywhere, I think this could be done with the application chooser window as well.

**Comment by sonnyp** [comment]
@gregorni sounds good – can you update your PR to wrap both windows in WindowHandle ?

**Comment by gregorni** [comment]
I made #114 for that, but if you want both changes in this one PR, I can also merge my `draggeable` branch into `flat-header`.

**Comment by sonnyp** [comment]
Related:

* https://gitlab.gnome.org/Teams/Design/hig-www/-/issues/70
* https://gitlab.gnome.org/GNOME/libadwaita/-/issues/507

**Review by sonnyp — APPROVED** [review]
Thanks!

**Comment by sonnyp** [comment]
BTW, if you're interested – Junction needs a better welcome/onboarding experience. 

We got this feedback in app reviews

> Really wish you could set it as the default for images and videos with a click of a button like you can with browsers, though.

**Pull request merged**
